=== shaavetha/Rustic-Rhythms/RusticRhythms/storefront/store.dtd
<!ELEMENT store (genre+)>
<!ELEMENT genre (details, album+)>
<!ATTLIST genre name CDATA #REQUIRED>
<!ELEMENT album (title, cover, artist, price, tracklist+, description)>
<!ATTLIST album id CDATA #REQUIRED>
<!ELEMENT tracklist (track+)>
<!ELEMENT details (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT cover (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT track (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== shaavetha/Rustic-Rhythms/RusticRhythms/albumlist/album.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="album.xsl"?>
<!DOCTYPE store SYSTEM "../storefront/store.dtd">

<!-- Anastasia Kajalic (M00982467) | Basma Sameer (M01040352) | Raghad Barmem (M01039213) | Shaavetha Mohankumar (M01039389) -->

<store>
	<music:genre name = "Pop" xmlns:music="http://RusticRhythmsXML.com/XML">
	<music:details>A genre known for catchy melodies and upbeat rhythms, Pop music spans decades with chart-topping hits and iconic artists, appealing to a wide audience with vibrant sounds and memorable lyrics.</music:details>
		<music:album id="1">
			<music:title>Norman F Rockwell!</music:title>
			<music:cover>../images/songs/image89.png</music:cover>
			<music:artist>Lana Del Rey</music:artist>
			<music:price>AED 230</music:price>
			<music:tracklist>
				<music:track>Norman F Rockwell</music:track>
				<music:track>Mariners Apartment Complex</music:track>
				<music:track>Venice B</music:track>
				<music:track>F it I love you</music:track>
				<music:track>Doin' Time</music:track>
				<music:track>Love song</music:track>
				<music:track>Cinnamon Girl</music:track>
				<music:track>How to disappear</music:track>
				<music:track>California</music:track>
				<music:track>The Next Best American Record</music:track>
				<music:track>The greatest</music:track>
				<music:track>Bartender</music:track>
				<music:track>Happiness is a butterfly</music:track>
				<music:track>hope is a dangerous thing for a woman like me to have - but i have it</music:track>
			</music:tracklist>
			<music:description>Norman F Rockwell! (abbreviated to NFR! in some releases) is the sixth studio music:album by American singer-songwriter Lana Del Rey, released on August 30, 2019, by Interscope and Polydor Records. The music:album was primarily produced by Del Rey and Jack Antonoff, with additional contributions from Zach Dawes, Andrew Watt, and longtime Del Rey collaborator Rick Nowels. Musically, Norman F Rockwell! explored a soft rock sound featuring psych-rock elements, piano ballads, and references to various classic rock artists. The mtitle of the album is a reference to painter and illustrator Norman Rockwell.</music:description>
		</music:album>
		
		<music:album id="2">
			<music:title>1989</music:title>
			<music:cover>../images/songs/image27.png</music:cover>
			<music:artist>Taylor Swift</music:artist>
			<music:price>AED 315</music:price>
			<music:tracklist>
				<music:track>Welcome to New York</music:track>
				<music:track>Blank Space</music:track>
				<music:track>Style</music:track>
				<music:track>Out of the Woods</music:track>
				<music:track>All You Had to Do Was Stay</music:track>
				<music:track>Shake It Off</music:track>
				<music:track>I Wish You Would</music:track>
				<music:track>Bad Blood</music:track>
				<music:track>Wildest Dreams</music:track>
				<music:track>How You Get the Girl</music:track>
				<music:track>This Love</music:track>
				<music:track>I Know Places</music:track>
				<music:track>Clean</music:track>
			</music:tracklist>
			<music:description>1989 is the fifth studio album by the American singer-songwriter Taylor Swift. It was released on October 27, 2014, by Big Machine Records. titled after Swift's birth year as a symbolic rebirth, the album recalibrated her music:artistic identity from country music to pop.</music:description>
		</music:album>
		
		<music:album id="3">
			<music:title>Anti</music:title>
			<music:cover>../images/songs/image58.png</music:cover>
			<music:artist>Rihanna</music:artist>
			<music:price>AED 275</music:price>
			<music:tracklist>
				<music:track>Consideration</music:track>
				<music:track>James Joint</music:track>
				<music:track>Kiss It Better</music:track>
				<music:track>Work</music:track>
				<music:track>Desperado</music:track>
				<music:track>Woo</music:track>
				<music:track>Needed Me</music:track>
				<music:track>Yeah, I Said It</music:track>
				<music:track>Same Ol' Mistakes</music:track>
				<music:track>Never Ending</music:track>
				<music:track>Love on the Brain</music:track>
				<music:track>Higher</music:track>
				<music:track>Close to You</music:track>
				<music:track>Goodnight Gotham</music:track>
				<music:track>Pose[Explicit]</music:track>
				<music:track>S With Me [Explicit]</music:track>
			</music:tracklist>
			<music:description>Anti is the eighth studio album by Barbadian singer Rihanna. It was released on 28 January 2016 by Roc Nation and Westbury Road. Rihanna started recording in 2014 after departing from Def Jam Recordings, who had released all of her albums since her 2005 debut. As executive producer, Rihanna recorded Anti with producers including Jeff Bhasker, Boi-1da, DJ Mustard, Hit-Boy, Brian Kennedy, Timbaland and No I.D., at studios in Canada, the United States and France.</music:description>
		</music:album>
		
		<music:album id="4">
			<music:title>Short n' Sweet</music:title>
			<music:cover>../images/songs/image3.png</music:cover>
			<music:artist>Sabrina Carpenter</music:artist>
			<music:price>AED 390</music:price>
			<music:tracklist>
				<music:track>Taste</music:track>
				<music:track>Good Graces</music:track>
				<music:track>Coincidence</music:track>
				<music:track>Espresso</music:track>
				<music:track>Slim Pickins</music:track>
				<music:track>Lie To Girls</music:track>
				<music:track>Please Please Please</music:track>
				<music:track>Sharpest Tool</music:track>
				<music:track>Bed Chem</music:track>
				<music:track>Dumb &amp; Poetic</music:track>
				<music:track>Juno</music:track>
				<music:track>Don't Smile</music:track>
			</music:tracklist>
			<music:description>Short n' Sweet is the sixth studio music:album by American singer Sabrina Carpenter. It was released on August 23, 2024, through Island Records. Primarily a pop record with country, folk, disco, bubblegum, rock and R&amp;B influences, Short n' Sweet was produced by Julian Bunetta, John Ryan, Ian Kirkpatrick, and Jack Antonoff. The music:album explores Carpenter's love life and her perspectives on 2020s dating. Its music:title is a reference to the emotional impact of her shortest romantic relationships, as well as her short stature and the music:album's brief runtime.</music:description>
		</music:album>
		
		<music:album id="5">
			<music:title>BRAT</music:title>
			<music:cover>../images/songs/image38.png</music:cover>
			<music:artist>Charli xcx</music:artist>
			<music:price>AED 350</music:price>
			<music:tracklist>
				<music:track>360</music:track>
				<music:track>Club classics</music:track>
				<music:track>Sympathy is a knife</music:track>
				<music:track>I might say something stupid</music:track>
				<music:track>Talk talk</music:track>
				<music:track>Everuthing is romantic</music:track>
				<music:track>Rewind</music:track>
				<music:track>So I</music:track>
				<music:track>Girl, so confusing</music:track>
				<music:track>Apple</music:track>
				<music:track>B2b</music:track>
				<music:track>Mean girls</music:track>
				<music:track>I think about it all the time</music:track>
				<music:track>365</music:track>
			</music:tracklist>
			<music:description>Brat is the sixth studio music:album by English singer Charli XCX, released through Atlantic Records on 7 June 2024. It features production by Charli XCX, her longtime executive producer A. G. Cook, Finn Keane, Cirkut, her partner George Daniel, and others. The music:album draws influence from the 2000s English rave music scene, with a more aggressive club sound than her previous music:album, Crash (2022).</music:description>
		</music:album>
		
		<music:album id="6">
			<music:title>GUTS</music:title>
			<music:cover>../images/songs/image64.png</music:cover>
			<music:artist>Olivia Rodrigo</music:artist>
			<music:price>AED 285</music:price>
			<music:tracklist>
				<music:track>all-american b*tch</music:track>
				<music:track>bad idea right?</music:track>
				<music:track>vampire</music:track>
				<music:track>lacy</music:track>
				<music:track>ballad of a homescholled girl</music:track>
				<music:track>making the bed</music:track>
				<music:track>logical</music:track>
				<music:track>get him back!</music:track>
				<music:track>love is embarassing</music:track>
				<music:track>the grudge</music:track>
				<music:track>pretty isn't pretty</music:track>
				<music:track>teenage dream</music:track>
			</music:tracklist>
			<music:description>Guts is the second studio music:album by American singer-songwriter Olivia Rodrigo, released on September 8, 2023, through Geffen Records. It was written and recorded with Rodrigo working closely alongside Dan Nigro, the producer and multi-instrumentalist of her debut music:album Sour (2021). Inspired by the period of time immediately following Sour's success, Rodrigo conceived Guts hoping to reflect the process of maturity she experienced toward the end of her teenage years.</music:description>
		</music:album>
		
		<music:album id="7">
			<music:title>Happier Than Ever</music:title>
			<music:cover>../images/songs/image71.png</music:cover>
			<music:artist>Billi Eilish</music:artist>
			<music:price>AED 245</music:price>
			<music:tracklist>
				<music:track>Getting Older</music:track>
				<music:track>I Didn't Change My Number</music:track>
				<music:track>Billie Bossa Nova</music:track>
				<music:track>my future</music:track>
				<music:track>Oxytocin</music:track>
				<music:track>GOLDWING</music:track>
				<music:track>Lost Cause</music:track>
				<music:track>Halley's Comet</music:track>
				<music:track>Not My Responsibility</music:track>
				<music:track>OverHeated</music:track>
				<music:track>Everybody Dies</music:track>
				<music:track>Your Power</music:track>
				<music:track>NDA</music:track>
				<music:track>Therefore I Am</music:track>
				<music:track>Happier Than Ever</music:track>
				<music:track>Male Fantasy</music:track>
			</music:tracklist>
